Resources:
  # Tabla de usuarios
  UsersTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      # Completamente opcional, recordemos que DynamoDB no requiere esquemas
      AttributeDefinitions:
        # ID Principal
        - AttributeName: id_user
          AttributeType: N
        # Nombre de usuario
        - AttributeName: email
          AttributeType: S
        # Password de usuario
        - AttributeName: password
          AttributeType: S
      # Necesario para definir indice principal
      # Como si fuera una base de datos normal, este seria nuestro primary key
      KeySchema:
        - AttributeName: id_user
          KeyType: HASH
      # Configuramos la capacidad de lectura/escritura de la tabla
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      # Si tuvieramos nombres dinamicos (por ejemplo, segun ambiente, lo podemos configurar aca)
      TableName: users

  